### ISSUE TITLE
How do you port Google Sites to GIithub

### ISSUE THREAD

**Issue by Heyayyu** [tw31120071857/BCHS-Unblocked-Games-V2#1]
Hi i was wondering how you ported the google sites to github

**Comment by tw31120071857** [comment]
1. Go to your google drive and create a new folder call it something like "website".
2. Locate your google site and move it into the folder you just created (This won't affect your website at all).
3. go to https://takeout.google.com/ and at the top click on "deselect all".
4. Scroll down to the "Drive" section and select it.
5. Click on "All drive data included".
6. Deselect "Include all files and folders in Drive".
7. Click on "Deselect all"
8. Select the folder containing your website.
9. Press ok.
10. Scroll down and press "next step".
11. Then press "Create export".
12. Go to your email and wait 5-10 minutes (depending on the size of your website).
13. You will receive and email titled "Your Google data is ready to download", Open it.
14. Click on "Download your files".
15. Login with your google account.
16. Download your website.
17. Open the extracted folder and go to /Takeout/Drive/(website folder name)/(name of website)/Published/.
18. There is all fo your website files.

**Comment by Heyayyu** [comment]
Thank You So Much!

**Comment by tw31120071857** [comment]
No Problem! Have a great day.
